project:
  type: book
  output-dir: _site

book:
  title: "my-ebook"
  author: "Parmeshvar"
  date: "7/6/2025"
  chapters:
    - index.qmd 
    # - part: Preface
    #   chapters:
    #     - why-read.qmd
    #     - Developing.qmd
    # - lec_1.qmd
    - introduction-to-statistics.qmd
    - basic-statistics1.qmd
    - basic-statistics2.qmd
    # - week1-statistics.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt

publish:
  site-url: https://parmeshvar8.github.io/ebook_1
