project:
  type: book
  output-dir: _site

book:
  title: "my-ebook"
  author: "Parmeshvar"
  date: "7/6/2025"
  chapters:
    # - part: Preface
    #   chapters:
    #     - why-read.qmd
    #     - Developing.qmd
    # - lec_1.qmd
    # - introduction-to-statistics.qmd
    - index.qmd 
    # - week1.qmd
    # - week2.qmd
    # - week3.qmd
    # - week4.qmd
    # - week5.qmd
    - week6.qmd
    # - week7.qmd
    # - week8.qmd
# /    - basic-statistics5.qmd
#     - basic-statistics6.qmd
#     - basic-statistics7.qmd
#     - week1.qmd
    # - week1-statistics.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
    papersize: letter
    classoption:
      - DIV=11
      - numbers=noendperiod
    header-includes:
      - \KOMAoption{captions}{tableheading}
      - \usepackage{enumitem}
      - \setlist[enumerate]{leftmargin=*,itemsep=0.5em,parsep=0.5em}
      - \setlist[itemize]{leftmargin=*,itemsep=0.5em,parsep=0.5em}
      - \setlist[description]{leftmargin=*,itemsep=0.5em,parsep=0.5em}
    geometry:
      - margin=1in


publish:
  site-url: https://parmeshvar8.github.io/ebook_1/
