---
title: "Introduction"
author: "Parmeshvar"
format:
  html:
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-sections: true
    documentclass: scrreprt
    papersize: letter
    classoption:
      - DIV=11
      - numbers=noendperiod
    header-includes:
      - \KOMAoption{captions}{tableheading}
      - \usepackage{enumitem}
      - \setlist[enumerate]{leftmargin=*,itemsep=0.5em}
      - \setlist[itemize]{leftmargin=*,itemsep=0.5em}
    geometry:
      - margin=1in


---

# Introduction

**DR.Harsh Pradhan**, [Phone: +91-9930034241 , Email: harsh.231284\@gmail.com](http://www.ling.uni-potsdam.de/en/), [Institute of Management Studies, Banaras Hindu University](http://www.uni-potsdam.de/en/university-of-potsdam.html), Address: 18-GF, Jaipuria Enclave, Kaushambhi, Ghaziabad, India, 201010\
**Interest**: [Goal Orientation     Job Performance     Consumer Behavior     Behavioral Finance     Bibiliometric Analysis     Options as Derivatives     Statistics     Indian Knowledge System](http://www.uni-potsdam.de/humfak/hum-forschungsschwerpunkte/forschungscluster-sprache.html),




[Orcid ID](https://orcid.org/0000-0002-3332-3610)\
[Google Scholar](https://scholar.google.com/citations?user=8l5MEd0AAAAJ&hl=en&oi=sra)\
[GitHub](https://github.com/)\
[Researcher ID](https://www.webofscience.com/wos/author/record/AIB)\
[Personal Website](http://https//sites.google.com/view/harshpradhan/home%20%20,%20%20%20%20%20shorturl.at/yzQSX)\
[Youtube ID](http://www.youtube.com/@dr.harshpradhan742)

**Doing a PhD with me:** [README.1st](http://www.ling.uni-potsdam.de/~vasishth/doingaphdwithme.html)

[Academic Profile](https://bhu.ac.in/Site/FacultyProfile/1_5?FA000562)

------------------------------------------------------------------------




Topics to be covered:

1.  Basic probability theory, random variable theory (including jointly distributed RVs), probability distributions (including bivariate distributions)
2.  Using Bayes' rule for statistical inference
3.  An introduction to (generalized) linear models
4.  An introduction to hierarchical models
5.  Measurement error models
6.  Mixture models
7.  Model selection and hypothesis testing (Bayes factor and k-fold cross-validation)

## Teaching
Science and statistics is/are one unitary thing; you cannot do one without the other. Towards this end, I teach some (in my opinion) critically important classes that provide a solid statistical foundation for doing research in cognitive science.

Courses offered:

1. Free online course, four weeks (MOOC), enrollments open: Introduction to Bayesian Data Analysis
2. Short (four-hour) tutorial on Bayesian statistics, taught at EMLAR 2022: here
3. Introduction to (frequentist) statistics
4. Introduction to Bayesian data analysis for cognitive science
5. BDA cover

## Lecture notes

Download from [here](https://drive.google.com/drive/folders/1H-jQNOqS3PLgdXADRYF7ag-WqN_tK4qc?usp=share_link).

## Moodle website

All communications with students in Potsdam will be done through [this website](https://moodle2.uni-potsdam.de/course/view.php?id=17526).
# 📘 Schedule

| **Week** | **Lecture** | **Main Topic**              | **Subtopic**                                | **🎥 Video**                                                                                  | **📄 PDF Resource**                                                                 |
|----------|-------------|-----------------------------|---------------------------------------------|-----------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
| Week 2   | 1           | Descriptive Statistics       | Central Tendency                            | [Video](https://youtu.be/9709cbHi4-8?t=173)                                                   | [Week 2.pdf](https://drive.google.com/file/d/1CXkLjlvsMt6-BcrDLrNPsTt6SIUSq7NG/view) |
|          | 2           | Descriptive Statistics       | Measure of Variability                      | [Video](https://youtu.be/Wn-buo8ARUY)                                                         | Same as above                                                                       |
|          | 3           | Descriptive Statistics       | Describing Data                             | [Video](https://youtu.be/LS9jxi9t06A)                                                         | Same as above                                                                       |
|          | 4           | Descriptive Statistics       | Probability                                 | [Video](https://youtu.be/DImY6pmX8UA)                                                         | Same as above                                                                       |
|          | 5           | Descriptive Statistics       | Distribution                                | [Video](https://youtu.be/RZVFQ_wlQBI)                                                         | Same as above                                                                       |
| Week 3   | 1           | Descriptive Statistics       | Z Table (Normal Distribution)               | [Video](https://youtu.be/mh92FQKFFlA)                                                         | [Week 3.pdf](https://drive.google.com/file/d/1sVwyzDjitecinjyR4LxbOafHe8ol0JIu/view) |
|          | 2           | Descriptive Statistics       | Measuring Divergence                        | [Video](https://youtu.be/SdghNy_5oe0)                                                         | Same as above                                                                       |
|          | 3           | Inferential Statistics       | Sample and Population                       | [Video](https://youtu.be/eYjtWoMb21s)                                                         | Same as above                                                                       |
|          | 4           | Inferential Statistics       | Model Fit                                   | [Video](https://youtu.be/1hdzMWcj5a0)                                                         | Same as above                                                                       |
|          | 5           | Inferential Statistics       | Hypothesis and Error                        | [Video](https://youtu.be/pP3yKhIgJQw)                                                         | Same as above                                                                       |
| Week 4   | 1           | Terms of Statistics          | Terms of Statistics                         | [Video](https://youtu.be/lO7jZJIlTgU)                                                         | [Week 4.pdf](https://drive.google.com/file/d/1dDDUXCdCBp6VxKbQzsnsIwQY-kZL8U3D/view) |
|          | 2           | Terms of Statistics          | T-Test                                      | [Video](https://youtu.be/4i-2uZ2LuXg)                                                         | Same as above                                                                       |
|          | 3           | Terms of Statistics          | T-Test in Detail                            | [Video](https://youtu.be/Vo48lLCR3yk)                                                         | Same as above                                                                       |
|          | 4           | ANOVA                        | ANOVA                                       | [Video](https://youtu.be/jz-lu_HtkXo)                                                         | Same as above                                                                       |
| Week 5   | 1           | ANOVA                        | Example of ANOVA                            | [Video](https://youtu.be/AQL2fVlc2EA)                                                         | [Week 5.pdf](https://drive.google.com/file/d/1f3LZJRQS-Lnxy0_kNaAASZppPJk8pUX_/view) |
|          | 2           | ANOVA                        | Types of ANOVA                              | [Video](https://youtu.be/MQ9GFyXZtQA)                                                         | Same as above                                                                       |
|          | 3           | Correlation                  | Introduction to Correlation                 | [Video](https://youtu.be/5zMCSIa2YqE)                                                         | Same as above                                                                       |
|          | 4           | Correlation                  | Regression (Part 1)                         | [Video](https://youtu.be/ELEeZNyySSM)                                                         | Same as above                                                                       |
|          | 5           | Correlation                  | Regression (Part 2)                         | [Video](https://youtu.be/3hJdWKV0alw)                                                         | Same as above                                                                       |
| Week 6   | 1           | Correlation                  | R Script for Regression                     | [Video](https://youtu.be/V151yC8cCMs)                                                         | [Week 6.pdf](https://drive.google.com/file/d/1mA1-nFxjmXK_QC8vbW4BhoKO6HNS0wZy/view) |
|          | 2           | Chi Square                   | Chi Square                                  | [Video](https://youtu.be/Z9DxCZzXAz4)                                                         | Same as above                                                                       |
|          | 3           | Chi Square                   | Chi Square Test                             | [Video](https://youtu.be/ZhUTidqrPbI)                                                         | Same as above                                                                       |
|          | 4           | Logistic Function            | Regression Function                         | [Video](https://youtu.be/3EXiuBJYTn4)                                                         | Same as above                                                                       |
|          | 5           | Logistic Function            | Distribution                                | [Video](https://youtu.be/9NhApiDlFrs)                                                         | Same as above                                                                       |
| Week 7   | 1           | Time Series                  | Intro to Time Series                        | [Video](https://youtu.be/t5z9cM-PgoQ)                                                         | [Week 7.pdf](https://drive.google.com/file/d/1ACloSOgbYVlxmqGfUe_mBDvirLJzCZnB/view) |
|          | 2           | Time Series                  | Conditional Probability                     | [Video](https://youtu.be/SjaJNBilHcM)                                                         | Same as above                                                                       |
|          | 3           | Time Series                  | Additional Concepts                         | [Video](https://youtu.be/pm1SXK0kFpg)                                                         | Same as above                                                                       |
|          | 4           | Time Series                  | Distribution                                | [Video](https://youtu.be/0V0UTi5fbPc)                                                         | Same as above                                                                       |
|          | 5           | Time Series                  | Poisson Distribution                        | [Video](https://youtu.be/MM-MkuJa_KY)                                                         | Same as above                                                                       |
|          | 6           | Index Numbers                | Price & Quantity Index                      | [Video](https://youtu.be/YZv8H2PlymQ)                                                         | Same as above                                                                       |
|          | 7           | Decision Environments        | Risk/Uncertainty, Bayes, Trees              | [Video](https://youtu.be/b0jP5anQiUg)                                                         | Same as above                                                                       |
|          | 8           | Time Series Analysis         | Components, Trend, Seasonality              | [Video](https://youtu.be/C77jZeYkBBU)                                                         | Same as above                                                                       |
|          | 9           | Time Series Analysis         | Least Squares Method                        | [Video](https://youtu.be/yiJjJaL7z5w)                                                         | Same as above                                                                       |
| Week 8   | 1           | Effect Size & Documentation  | Package/Library                             | [Video](https://youtu.be/C77jZeYkBBU)                                                         | [Week 8.pdf](https://drive.google.com/file/d/1dUv8rXI3vhsMkBcYnlStYg-xJpYtCYSF/view) |
|          | 2           | Effect Size & Documentation  | RStudio vs RKward                           | [Video](https://youtu.be/Z9DxCZzXAz4)                                                         | Same as above                                                                       |
|          | 3           | Effect Size & Documentation  | Flexplot                                    | [Video](https://youtu.be/ZhUTidqrPbI)                                                         | Same as above                                                                       |
|          | 4           | Effect Size & Documentation  | Functions                                   | [Video](https://youtu.be/3EXiuBJYTn4)                                                         | Same as above                                                                       |
|          | 5           | Effect Size & Documentation  | R Shiny & R Markdown                        | [Video](https://youtu.be/9NhApiDlFrs)                                                         | Same as above                                                                       |
|          | 6           | Effect Size & Documentation  | Application with Real Datasets              | [Video](https://youtu.be/t5z9cM-PgoQ)                                                         | Same as above                                                                       |
|          | 7           | Effect Size & Interpretation | Importance in Testing                       | [Video](https://youtu.be/SjaJNBilHcM)                                                         | Same as above                                                                       |
|          | 8           | Effect Size & Interpretation | Installing dplyr, ggplot2                   | [Video](https://youtu.be/MM-MkuJa_KY)                                                         | Same as above                                                                       |
|          | 9           | Effect Size & Interpretation | Visual Model Interpretation                 | [Video](https://youtu.be/YZv8H2PlymQ)                                                         | Same as above                                                                       |
|          | 10          | Effect Size & Interpretation | Creating/Using Functions                    | [Video](https://youtu.be/b0jP5anQiUg)                                                         | Same as above                                                                       |
|          | 11          | Effect Size & Interpretation | Report, Dashboard, Interactivity            | [Video](https://youtu.be/C77jZeYkBBU)                                                         | Same as above                                                                       |
